export const en = {
  // Header
  header: {
    viewPlans: 'View Plans',
    login: 'Login',
    signUp: 'Sign Up',
    premium: 'Premium',
  },

  // Sidebar
  sidebar: {
    newImage: 'New Image',
    recentAnalysis: 'Recent Analysis',
    expand: 'Expand sidebar',
    collapse: 'Collapse sidebar',
    settings: 'Settings',
    logout: 'Logout',
    highConfidence: 'High confidence',
    mediumConfidence: 'Medium confidence',
    lowConfidence: 'Low confidence',
  },

  // Settings Panel
  settings: {
    general: 'General',
    account: 'Account',
    appearance: 'Appearance',
    notifications: 'Notifications',
    privacy: 'Privacy and Security',
    fullName: 'Full name',
    email: 'Email',
    plan: 'Plan',
    theme: 'Theme',
    language: 'Language',
    emailNotifications: 'Email notifications',
    changePassword: 'Change password',
    dataPrivacy: 'Data privacy',
    lightMode: 'Light',
    darkMode: 'Dark',
    systemMode: 'System',
    spanish: 'Español',
    english: 'English',
    change: 'Change',
  },

  // Home Page
  home: {
    title: 'AI-Generated Image Detector',
    description: 'Uses Machine Learning algorithms to determine if an image was created by artificial intelligence',
    analyzeButton: 'Analyze with AI',
    uploadingToServer: 'Uploading image to server...',
    processingAI: 'Analyzing with AI...',
  },

  // Dashboard
  dashboard: {
    newAnalysis: 'New Analysis',
    analysisResult: 'Analysis Result',
    savedAnalysis: 'Saved Analysis',
    analyzeWithAI: 'Analyze with AI',
    exportCSV: 'Export CSV',
    analyzeAnother: 'Analyze another image',
    analyzing: 'Analyzing image...',
    imageLoaded: 'Image loaded successfully',
    loadingAnalysis: 'Loading analysis...',
  },

  // Login
  login: {
    title: 'Login',
    email: 'Email',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot your password?',
    loginButton: 'Login',
    noAccount: "Don't have an account?",
    signUpHere: 'Sign up here',
    continueWithout: 'Continue without account',
  },

  // Register
  register: {
    title: 'Create Account',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm password',
    acceptTerms: 'I accept the terms and conditions',
    createAccount: 'Create Account',
    haveAccount: 'Already have an account?',
    loginHere: 'Login here',
    continueWithout: 'Continue without account',
    passwordMismatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters',
  },

  // Pricing
  pricing: {
    free: 'Free',
    premium: 'Premium',
    recommended: 'RECOMMENDED',
    useFree: 'Use Free',
    subscribeNow: 'Subscribe Now',
  },

  // Analysis Results
  analysis: {
    result: 'Result',
    realImage: 'Real Image',
    realImageDesc: 'This image appears to be a real photograph or natural image',
    aiGenerated: 'AI Generated',
    aiGeneratedDesc: 'This image appears to have been generated by artificial intelligence',
    highConfidence: 'High Confidence',
    mediumConfidence: 'Medium Confidence',
    lowConfidence: 'Low Confidence',
    probabilities: 'Probabilities',
    detailedAnalysis: 'Detailed Analysis',
    colorAnalysis: 'Color Analysis',
    transparency: 'Transparency',
    noiseAnalysis: 'Noise Analysis',
    watermarks: 'Watermarks',
    symmetry: 'Symmetry',
    featureScores: 'Feature Scores',
    modelVersion: 'Model Version',
    downloadPdf: 'Download PDF Report',
    downloading: 'Downloading...',
    premiumFeature: 'Premium Feature',
    upgradeToPdf: 'Upgrade to Premium to download detailed PDF reports',
  },

  // Image Uploader
  uploader: {
    dragDrop: 'Drag an image here',
    orClick: 'or click to select',
    selectFile: 'Select File',
    fileTypes: 'PNG, JPG, GIF up to 10MB',
    analyzing: 'Analyzing image...',
    pleaseWait: 'Please wait',
  },

  // Common
  common: {
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
  },
};
